apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: flask-canary
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      name: backend
      creationTimestamp: null
      labels:
        role: backend
        env: canary
        app: flask
    spec:
      containers:
      - image: gcr.io/general-218816/flask:master.444
        name: backend
        resources: {}
        ports:
        - name: http
          containerPort: 80
status: {}
