kind: Service
apiVersion: v1
metadata:
  name: flask-backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: flask
    role: backend